fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app_user:
    resource: "@AppUserBundle/Controller/"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
